apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: koel-image_storage-pv
  namespace: koel
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-static
  resources:
    requests:
      storage: 1Ti
